name: Veracode IaC/Secrets Scanning

run-name: Veracode IaC/Secrets Scanning - ${{ github.event.client_payload.repository.name }}

on:
  repository_dispatch:
    types: [veracode-iac-secrets-scan]
    
jobs:
  register:
    uses: ./.github/workflows/veracode-check-run.yml
    with:
      check_run_name: ${{ github.workflow }}
      head_sha: ${{ github.event.client_payload.sha }}
      repositroy_owner: ${{ github.event.client_payload.repository.owner }}
      repositroy_name: ${{ github.event.client_payload.repository.name }}
      event_type: ${{ github.event.client_payload.event_type }}
      github_token: ${{ github.event.client_payload.token }}
      run_id: ${{ github.run_id }}
       
  veracode-iac-secrets-scan:
    needs: [register]
    runs-on: ubuntu-latest
    name: Veracode IaC/Secrets Scanning

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository.full_name }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ github.event.client_payload.token }}
      - name: Run Veracode IaC/Secrets Scanning
        uses: veracode/container_iac_secrets_scanning@v1.0.1
        with:
            vid: ${{ secrets.VERACODE_API_ID }}
            vkey: ${{ secrets.VERACODE_API_KEY }}
            command: "scan" 
            type: "directory"
            source: "./"
            format: "json"
            debug: false
            fail_build: true
